# -*- coding: utf-8 -*-
"""Spotify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVkjsuJRi5sQ46OUO8SZkNLKyaSWcAN-
"""

!pip install requests

import requests
import datetime

import base64

client_id = 'CLIENT ID'
client_secret = 'CLIENT SECRET ID'

client_creds = f"{client_id}:{client_secret}"
type(client_creds)

client_creds_b64 = base64.b64encode(client_creds.encode())
type(client_creds_b64)

#base64.b64decode(client_creds_b64)

token_url="https://accounts.spotify.com/api/token"
method = "POST"
token_data = {
    "grant_type" : "client_credentials"
}
token_header = {
    "Authorization" : f"Basic {client_creds_b64.decode()}" #Basic <base64 encoded client_id:client_secret>
}

r = requests.post(token_url, data=token_data, headers=token_header)
print(r.json())
valid_request = r.status_code in range(200, 299)

if valid_request:
  token_response_data = r.json()
  now = datetime.datetime.now()
  access_token = token_response_data['access_token']
  expires_in = token_response_data['expires_in'] #seconds
  expires = now + datetime.timedelta(seconds=expires_in)
  did_expire = expires < now
